Michhhuang/tri 83 allow user to select attributes to measure biasfairness for
byebyebias/byebyebias pull request #42
Opened 2024-11-16 02:05 UTC by 1michhu1

https://github.com/user-attachments/assets/f27d722e-89b9-4e27-8f2e-8f0d335aed73

- Create new route for uploading file
- link is currently dummy
- accessibility is still work in progress, committing rn so the s3 link can be connected 
- attribute value selection are dummy right now

2024-11-16 03:52 UTC, 1zhaohel commented on frontend/src/views/pages/UploadPage/UploadPage.tsx
> +                                backgroundColor: "#00CF31",
is it possible to put the stylings into a css file/create a component with the styling?

2024-11-16 03:54 UTC, 1zhaohel commented
looks really good :D btw just looking off of the preview netlify link, should the button on main be routing to the upload page?

2024-11-17 00:44 UTC, aerymist approved these changes

2024-11-17 02:59 UTC, aakshataa approved these changes
Looks great!

2024-11-18 21:44 UTC, aakshataa requested changes
these are just nitpicky comments:

- increase the size of Choose File and decrease the size of Upload (to make them around the same height)
- if possible can the 'or' text and the filename be changed to use the same font as the rest of the page?
- Add footer to the upload page 

Thank You!

2024-11-21 05:12 UTC, aakshataa approved these changes
Looks good!!

2024-11-24 22:26 UTC, merged

2024-11-25 00:12 UTC, chloehylee commented
I know this is already merged but I was just running through main again, and I was wondering if we should have some sort of indicator to show that something is selected? B/c right now after an attribute is selected the user has to manually remember which ones they chose already.