1zhaohel/tri 106 Debug Fairness Score Issue
byebyebias/byebyebias pull request #56
Opened 2024-11-26 20:27 UTC by 1zhaohel

**Description**
Previously, different transactions with varied biases would achieve a low fairness score. For example, very biased dataset receives a F and no bias dataset receives a D-. 

Instead, using accuracy as the score seems to be more reflective of the datasets. Very biased dataset now receives a C and no bias dataset receives an A+. 

Additionally, refactored clean_dataset to use protected_attributes instead of hardcode.

2024-11-26 20:32 UTC, 1zhaohel commented
Also ig netlify preview only displays frontend changes because the backend changes are not reflected in the link.

2024-11-27 03:03 UTC, aakshataa commented
I think this accuracy score is important to include in our algorithm, but I think we should continue to use our statistical metrics since they are a core part of our program. Maybe instead, we can 'scale' our scores to reflect the bias in our test datasets. 

For example, our 'no bias' dataset should have a high score (~A). If we use this as our best score, we can scale everything enough to where this D- changes to an A. Every other datasets score should follow from that. 

Another option is to also modify the 'ranges' of fairness

2024-11-27 04:51 UTC, 1zhaohel commented
Now No Bias gives A+, Biased gives F and Medium gives C+

2024-11-27 21:34 UTC, aakshataa requested changes

2024-11-28 02:05 UTC, 1zhaohel commented on frontend/src/views/components/Dashboard/BiasScore/BiasScore.tsx
> +                <Typography variant="h1">{score}</Typography>
good catch!

2024-11-28 02:05 UTC, 1zhaohel commented on backend/core/entities/bias_metrics.py
> +    # def get_accuracy(self) -> float:
I think we will use this function in the overview so it's fine to leave it in for now

2024-11-28 02:14 UTC, 1michhu1 approved these changes
yep, looks good to me (discussed changes and questions in person)

2024-11-28 02:17 UTC, merged